name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: Build app
      run: npm run build
    - name: Deploy to S3
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::453639698538:user/serverless-admin
        aws-region: us-east-1
    - name: Sync build artifacts to S3
      run: aws s3 sync ./build s3://mfe1-alpha --delete --acl public-read
