name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.5.1
    - name: Install dependencies
      run: npm install
    - name: Build app
      run: npm run build
    - name: Deploy to S3
      uses: aws-actions/configure-aws-credentials@v1.4.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Sync build artifacts to S3
      run: aws s3 sync ./build s3://mfe1-alpha --delete --acl public-read
